### ISSUE TITLE
matrixMultiplyImpl3的计算结果似乎不对？

### ISSUE THREAD

**Issue by Miroier** [zh0ngtian/cuda_learning#1]
在run函数中，设置check_value=true，func_idx=3，会输出not equal

**Comment by Miroier** [comment]
除了func_idx=5时会输出equal，func_idx=0~4都会输出not equal，为什么会这样呢

**Comment by zh0ngtian** [comment]
你好，请问在你的测试 mnk 使用的是多少？

**Comment by Miroier** [comment]
是test.sh中写的值，我只改动了matmul.cu中的check_value=true、benchmark=false和func_idx这三个值

**Comment by zh0ngtian** [comment]
很奇怪的问题，我这边跑了一下，都是 is equal。你可以把结果打印出来看看是哪里不一样？

**Comment by Miroier** [comment]
抱歉，不是您代码的问题，在我把test.sh中指定的计算能力从75改到80后结果正确，打扰了😂

**Comment by zh0ngtian** [comment]
没关系，跑通了就行
